import json
from pathlib import Path
from local_llm_planner import plan_with_local_llm
import sys

# NOTE: The path to function_tools.json is hardcoded for demo. Make configurable for production use.
TOOLS_PATH = Path(__file__).parent.parent / 'data' / 'function_tools.json'

def load_tools():
    if not TOOLS_PATH.exists():
        print(f"Error: {TOOLS_PATH} not found. Please ensure the tool schema is available.")
        sys.exit(1)
    with open(TOOLS_PATH, 'r', encoding='utf-8') as f:
        return json.load(f)

def main():
    print("\n=== Toolmate (Open-Source LLM Edition) ===\n")
    tools = load_tools()
    user_query = input("Enter your request: ")
    plan = plan_with_local_llm(user_query, tools)
    print("\n--- Plan Generated by Local LLM ---\n")
    print(json.dumps(plan, indent=2))

if __name__ == "__main__":
    main() 